issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

# Enable built-in web interface
web:
  http: 0.0.0.0:5556

# Logger configuration
logger:
  level: "debug"
  format: "text"

# OAuth2 configuration
oauth2:
  skipApprovalScreen: true

# Static clients - applications that can use Dex
staticClients:
- id: llm-gateway
  redirectURIs:
  - 'http://localhost:3000/callback/'
  name: 'LLM Gateway'
  secret: dex-client-secret

# Enable password authentication
enablePasswordDB: true

# Static users for testing
staticPasswords:
- email: "admin@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
- email: "test@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "testuser"
  userID: "41331323-6f44-45e6-b3b9-0c5928b74de0"

# Static groups (optional)
staticGroups:
- id: admin
  name: Administrators
  members:
  - admin@example.com
- id: users
  name: Users
  members:
  - test@example.com
  - admin@example.com

# Frontend configuration
frontend:
  theme: "light"
  logoURL: ""
  issuer: "LLM Gateway"
  issuerURL: "http://localhost:3000"